Repository kevin218/Eureka, pull requests merged in 2022-07, with the labels that each got.

#365 Fixing time array for NGTS-10b MIRI new_drift files
  src/eureka/S3_data_reduction/miri.py
Labels: bug

#369 Add ability to download HST data using MAST API
  demos/HST/download_data_HST_template.py
  setup.cfg
  src/eureka/lib/mastDownload.py
Labels: enhancement

#370 Bug patches and log tweaks
  src/eureka/S3_data_reduction/bright2flux.py
  src/eureka/S3_data_reduction/miri.py
  src/eureka/S3_data_reduction/nircam.py
  src/eureka/S3_data_reduction/nirspec.py
  src/eureka/S3_data_reduction/plots_s3.py
  src/eureka/S3_data_reduction/s3_reduce.py
  src/eureka/S4_generate_lightcurves/s4_genLC.py
  src/eureka/S5_lightcurve_fitting/fitters.py
  src/eureka/S5_lightcurve_fitting/lightcurve.py
  src/eureka/S5_lightcurve_fitting/likelihood.py
  src/eureka/S5_lightcurve_fitting/plots_s5.py
  src/eureka/S6_planet_spectra/s6_spectra.py
  src/eureka/lib/clipping.py
  src/eureka/lib/manageevent.py
  src/eureka/lib/util.py
  tests/__init__.py
Labels: bug

#373 Updating jwst package version to 1.6.0
  demos/HST/S3_wfc3_template.ecf
  demos/JWST/S3_miri_lrs_template.ecf
  demos/JWST/S3_nircam_wfss_template.ecf
  demos/JWST/S3_nirspec_fs_template.ecf
  docs/media/S3_template.ecf
  docs/source/ecf.rst
  environment.yml
  setup.cfg
  src/eureka/S1_detector_processing/ramp_fitting.py
  src/eureka/S3_data_reduction/s3_reduce.py
  src/eureka/S3_data_reduction/source_pos.py
  src/eureka/S3_data_reduction/wfc3.py
  tests/MIRI_ecfs/S3_MIRI.ecf
  tests/NIRCam_ecfs/S3_NIRCam.ecf
  tests/NIRSpec_ecfs/S3_NIRSpec.ecf
  tests/WFC3_ecfs/S3_WFC3.ecf
Labels: bug, enhancement

#376 Adding S4 white-light output, S5 white-light constrained fits
  demos/HST/s5_fit_par_wfc3_template.epf
  demos/JWST/S4_template.ecf
  demos/JWST/S5_fit_par_template.epf
  docs/media/S4_template.ecf
  docs/media/S5_fit_par_template.epf
  docs/source/ecf.rst
  src/eureka/S4_generate_lightcurves/plots_s4.py
  src/eureka/S4_generate_lightcurves/s4_genLC.py
  src/eureka/S5_lightcurve_fitting/fitters.py
  src/eureka/S5_lightcurve_fitting/lightcurve.py
  src/eureka/S5_lightcurve_fitting/plots_s5.py
  src/eureka/S5_lightcurve_fitting/s5_fit.py
  src/eureka/lib/clipping.py
  src/eureka/lib/readEPF.py
  tests/MIRI_ecfs/S4_MIRI.ecf
  tests/MIRI_ecfs/s5_fit_par.epf
  tests/NIRCam_ecfs/S4_NIRCam.ecf
  tests/NIRCam_ecfs/S5_fit_par.epf
  tests/NIRSpec_ecfs/S4_NIRSpec.ecf
  tests/NIRSpec_ecfs/S5_fit_par.epf
  tests/WFC3_ecfs/S4_WFC3.ecf
Labels: enhancement

#372 Documentation Updates, v0.2
  docs/source/index.rst
  docs/source/installation.rst
  setup.cfg
  src/eureka/version.py
Labels: documentation

#382 Allowing iterative sigma clipping
  setup.cfg
  src/eureka/lib/clipping.py
  src/eureka/version.py
Labels: enhancement

#385 Fixing NaNs in source_pos with real data
  src/eureka/S3_data_reduction/plots_s3.py
  src/eureka/S3_data_reduction/s3_reduce.py
  src/eureka/S3_data_reduction/source_pos.py
  src/eureka/S3_data_reduction/wfc3.py
  src/eureka/lib/util.py
Labels: bug

#387 Fixing the start_from_oldchain_emcee function
  src/eureka/S5_lightcurve_fitting/fitters.py
Labels: bug, LC Fit

#383 Adding new StepModel to fit step-functions
  demos/HST/S5_wfc3_template.ecf
  demos/HST/s5_fit_par_wfc3_template.epf
  demos/JWST/S5_fit_par_template.epf
  demos/JWST/S5_template.ecf
  docs/media/S5_fit_par_template.epf
  docs/media/S5_template.ecf
  docs/source/ecf.rst
  src/eureka/S5_lightcurve_fitting/models/StepModel.py
  src/eureka/S5_lightcurve_fitting/models/__init__.py
  src/eureka/S5_lightcurve_fitting/s5_fit.py
  tests/MIRI_ecfs/S5_MIRI.ecf
  tests/MIRI_ecfs/s5_fit_par.epf
  tests/NIRCam_ecfs/S5_NIRCam.ecf
  tests/NIRCam_ecfs/S5_fit_par.epf
  tests/NIRSpec_ecfs/S5_NIRSpec.ecf
  tests/NIRSpec_ecfs/S5_fit_par.epf
Labels: enhancement, NIRCam

#392 More useful error message if no FITS files found
  src/eureka/S1_detector_processing/s1_process.py
  src/eureka/S2_calibrations/s2_calibrate.py
  src/eureka/S3_data_reduction/s3_reduce.py
  src/eureka/lib/util.py
Labels: bug

#390 Fixing time arrays for real data
  src/eureka/S3_data_reduction/miri.py
  src/eureka/S3_data_reduction/nircam.py
  src/eureka/S3_data_reduction/nirspec.py
Labels: bug

#393 Trying out automatic version numbering
  .github/workflows/flake8_linting.yml
  .github/workflows/pytest_testing.yml
  .gitignore
  docs/source/conf.py
  docs/source/ecf.rst
  pyproject.toml
  setup.cfg
  src/eureka/S3_data_reduction/source_pos.py
  src/eureka/S4_generate_lightcurves/s4_genLC.py
  src/eureka/version.py
Labels: enhancement

#405 Fixing MIRI gain file
  src/eureka/S2_calibrations/s2_calibrate.py
  src/eureka/S3_data_reduction/bright2flux.py
Labels: bug

#406 Tweaking S5 EPF template to use scatter_mult
  demos/JWST/S5_fit_par_template.epf
  docs/media/S5_fit_par_template.epf
Labels: bug, documentation

#424 M1 installation instructions and quickstart typo
  demos/JWST/S4_template.ecf
  demos/JWST/S5_template.ecf
  docs/source/faq.rst
  docs/source/installation.rst
  docs/source/quickstart.rst
Labels: documentation

#420 Allowing manual clipping and unbinned spectra from S4
  demos/HST/S4_wfc3_template.ecf
  demos/HST/S5_wfc3_template.ecf
  demos/JWST/S4_template.ecf
  demos/JWST/S5_template.ecf
  docs/media/S4_template.ecf
  docs/media/S5_template.ecf
  docs/source/ecf.rst
  src/eureka/S2_calibrations/s2_calibrate.py
  src/eureka/S4_generate_lightcurves/plots_s4.py
  src/eureka/S4_generate_lightcurves/s4_genLC.py
  src/eureka/S4_generate_lightcurves/wfc3.py
  src/eureka/S5_lightcurve_fitting/models/Model.py
  src/eureka/S5_lightcurve_fitting/s5_fit.py
  src/eureka/lib/util.py
  tests/MIRI_ecfs/S4_MIRI.ecf
  tests/MIRI_ecfs/S5_MIRI.ecf
  tests/NIRCam_ecfs/S4_NIRCam.ecf
  tests/NIRCam_ecfs/S5_NIRCam.ecf
  tests/NIRSpec_ecfs/S4_NIRSpec.ecf
  tests/NIRSpec_ecfs/S5_NIRSpec.ecf
  tests/WFC3_ecfs/S4_WFC3.ecf
Labels: bug, enhancement
