Repository kevin218/Eureka, pull requests merged in 2022-10, with the labels that each got.

#474 JOSS review edits and NIRCam wavelength
  docs/media/stage3_quickstart.png
  docs/media/stage3_quickstart1.png
  docs/media/stage3_quickstart2.png
  docs/media/stage4_quickstart.png
  docs/media/stage5_quickstart.png
  docs/media/stage6_quickstart.png
  docs/source/ecf.rst
  docs/source/quickstart.rst
  setup.cfg
  src/eureka/S3_data_reduction/nircam.py
  src/eureka/S3_data_reduction/optspex.py
  src/eureka/S4_generate_lightcurves/s4_genLC.py
  src/eureka/S5_lightcurve_fitting/models/CentroidModel.py
  src/eureka/S6_planet_spectra/s6_spectra.py
  src/eureka/__init__.py
Labels: documentation, enhancement

#477 Adding JOSS Paper Draft to Main
  .github/workflows/draft-pdf.yml
  demos/HST/S3_wfc3_template.ecf
  demos/HST/S4_wfc3_template.ecf
  demos/HST/S5_wfc3_template.ecf
  demos/HST/S6_wfc3_template.ecf
  demos/HST/run_eureka_wfc3.py
  demos/JWST/S1_miri_template.ecf
  demos/JWST/S1_nirx_template.ecf
  demos/JWST/S2_imaging_template.ecf
  demos/JWST/S2_miri_lrs_template.ecf
  demos/JWST/S2_nircam_wfss_template.ecf
  demos/JWST/S2_nirspec_fs_template.ecf
  demos/JWST/S3_miri_lrs_template.ecf
  demos/JWST/S3_nircam_photometry_template.ecf
  demos/JWST/S3_nircam_wfss_template.ecf
  demos/JWST/S3_nirspec_fs_template.ecf
  demos/JWST/S4_template.ecf
  demos/JWST/S5_template.ecf
  demos/JWST/S6_template.ecf
  demos/JWST/run_eureka.py
  demos/README
  docs/media/S1_template.ecf
  docs/media/S2_template.ecf
  docs/media/S3_template.ecf
  docs/media/S4_template.ecf
  docs/media/S5_template.ecf
  docs/media/S6_template.ecf
  docs/source/index.rst
  docs/source/quickstart.rst
  joss/figures/stages_flowchart.png
  joss/paper.bib
  joss/paper.md
Labels: documentation

#475 Write S5 LC files to a single Xarray file in Stage 6
  src/eureka/S5_lightcurve_fitting/s5_fit.py
  src/eureka/S6_planet_spectra/s6_spectra.py
Labels: enhancement
