Repository kevin218/Eureka, pull requests merged in 2022-03, with the labels that each got.

#152 Issue 145
  demos/HST/run_eureka_wfc3.py
  demos/JWST/run_eureka.py
  eureka/S1_detector_processing/s1_process.py
  eureka/S2_calibrations/s2_calibrate.py
  eureka/S3_data_reduction/s3_reduce.py
  eureka/S4_generate_lightcurves/s4_genLC.py
  eureka/S5_lightcurve_fitting/parameters.py
  eureka/S5_lightcurve_fitting/s5_fit.py
  eureka/S6_planet_spectra/s6_spectra.py
  eureka/lib/readECF.py
  eureka/tests/NIRCam_ecfs/S3_NIRCam.ecf
  eureka/tests/NIRCam_ecfs/S4_NIRCam.ecf
  eureka/tests/NIRCam_ecfs/S5_NIRCam.ecf
  eureka/tests/NIRCam_ecfs/S5_fit_par.ecf
  eureka/tests/NIRSpec_ecfs/S2_NIRSpec.ecf
  eureka/tests/NIRSpec_ecfs/S3_NIRSpec.ecf
  eureka/tests/NIRSpec_ecfs/S4_NIRSpec.ecf
  eureka/tests/NIRSpec_ecfs/S5_NIRSpec.ecf
  eureka/tests/NIRSpec_ecfs/S5_fit_par.ecf
  eureka/tests/S3_MIRI.ecf
  eureka/tests/test_general.py
Labels: enhancement

#156 Resolving Issue #144
  eureka/S3_data_reduction/plots_s3.py
  eureka/S3_data_reduction/s3_reduce.py
  eureka/S3_data_reduction/source_pos.py
  eureka/tests/test_lightcurve_fitting.py
Labels: bug

#164 Minor enhancements to Stages 5 + 6
  demos/JWST/S6_template.ecf
  eureka/S5_lightcurve_fitting/limb_darkening_fit.py
  eureka/S6_planet_spectra/plots_s6.py
  eureka/S6_planet_spectra/s6_spectra.py
Labels: enhancement

#160 Edits to get Eureka to work with new MIRI simulations
  demos/JWST/S5_template.ecf
  docs/media/S5_template.ecf
  eureka/S3_data_reduction/miri.py
  eureka/S4_generate_lightcurves/plots_s4.py
  eureka/S4_generate_lightcurves/s4_genLC.py
  eureka/S5_lightcurve_fitting/fitters.py
  eureka/S5_lightcurve_fitting/limb_darkening_fit.py
  eureka/S5_lightcurve_fitting/models/BatmanModels.py
  eureka/S5_lightcurve_fitting/plots_s5.py
  eureka/lib/astropytable.py
  eureka/tests/NIRCam_ecfs/S5_NIRCam.ecf
  eureka/tests/NIRSpec_ecfs/S5_NIRSpec.ecf
Labels: bug, enhancement

#163 Addressed memory leak in S3/S4 plotting, new defaults for NIRSpec S3 ecf
  demos/JWST/S3_nirspec_fs_template.ecf
  eureka/S3_data_reduction/plots_s3.py
  eureka/S4_generate_lightcurves/plots_s4.py
Labels: bug, enhancement

#153 Resolves #151 Issue with scatter_ppm
  eureka/S5_lightcurve_fitting/fitters.py
  eureka/S5_lightcurve_fitting/likelihood.py
  eureka/S5_lightcurve_fitting/plots_s5.py
Labels: bug

#166 Automating ancil file download
  demos/JWST/S3_miri_lrs_template.ecf
  demos/JWST/S3_nircam_wfss_template.ecf
  demos/JWST/S3_nirspec_fs_template.ecf
  docs/media/S3_template.ecf
  docs/source/ecf.rst
  docs/source/quickstart.rst
  eureka/S3_data_reduction/bright2flux.py
  eureka/S3_data_reduction/miri.py
  eureka/S3_data_reduction/nircam.py
  eureka/S3_data_reduction/niriss.py
  eureka/S3_data_reduction/nirspec.py
  eureka/S3_data_reduction/plots_s3.py
  eureka/S3_data_reduction/s3_reduce.py
  eureka/S5_lightcurve_fitting/plots_s5.py
  eureka/tests/NIRCam_ecfs/S3_NIRCam.ecf
  eureka/tests/NIRSpec_ecfs/S3_NIRSpec.ecf
Labels: bug, enhancement

#185 Only rotating xwindow ywindow once
  eureka/S3_data_reduction/s3_reduce.py
Labels: bug

#173 Allowing user defined wavelength bins in Stage 4
  eureka/S4_generate_lightcurves/s4_genLC.py
Labels: enhancement

#186 Allow background subtracted FITS files to be saved
  demos/HST/S3_wfc3_template.ecf
  demos/JWST/S3_miri_lrs_template.ecf
  demos/JWST/S3_nircam_wfss_template.ecf
  demos/JWST/S3_nirspec_fs_template.ecf
  docs/media/S3_template.ecf
  eureka/S3_data_reduction/background.py
  eureka/tests/NIRCam_ecfs/S3_NIRCam.ecf
  eureka/tests/NIRSpec_ecfs/S3_NIRSpec.ecf
Labels: enhancement

#180 Added CRDS env var instructions to installation page.
  .gitignore
  docs/source/contribute.md
  docs/source/installation.rst
Labels: documentation

#168 Masked arrays in S5
  eureka/S4_generate_lightcurves/plots_s4.py
  eureka/S5_lightcurve_fitting/lightcurve.py
  eureka/S5_lightcurve_fitting/plots_s5.py
  eureka/S5_lightcurve_fitting/s5_fit.py
  eureka/S6_planet_spectra/plots_s6.py
  eureka/S6_planet_spectra/s6_spectra.py
Labels: bug

#189 Added CRDS vars to README, added sphinx-rtd-theme to requirements
  README.md
  requirements.txt
Labels: documentation

#179 Parallel processing in emcee and dynesty fitters
  demos/JWST/S5_template.ecf
  docs/media/S5_template.ecf
  eureka/S5_lightcurve_fitting/fitters.py
  eureka/S5_lightcurve_fitting/lightcurve.py
  eureka/S5_lightcurve_fitting/likelihood.py
  eureka/S5_lightcurve_fitting/models/BatmanModels.py
  eureka/S5_lightcurve_fitting/plots_s5.py
  eureka/S5_lightcurve_fitting/s5_fit.py
  eureka/S5_lightcurve_fitting/utils.py
  eureka/tests/NIRCam_ecfs/S5_NIRCam.ecf
  eureka/tests/NIRSpec_ecfs/S5_NIRSpec.ecf
Labels: enhancement

#200 Resolve #182 by auto setting wave_min/max if None
  demos/JWST/S4_template.ecf
  docs/media/S4_template.ecf
  docs/source/ecf.rst
  eureka/S4_generate_lightcurves/s4_genLC.py
  eureka/tests/NIRCam_ecfs/S4_NIRCam.ecf
  eureka/tests/NIRSpec_ecfs/S4_NIRSpec.ecf
Labels: enhancement

#211 Removing requirement for astropy<5.0.0
  requirements.txt
Labels: bug, enhancement

#205 Only one plt.figure per type, overwrite if need
  eureka/S2_calibrations/s2_calibrate.py
  eureka/S4_generate_lightcurves/plots_s4.py
  eureka/S5_lightcurve_fitting/plots_s5.py
Labels: enhancement

#203 Implementing lcmayor's bug patch
  eureka/S5_lightcurve_fitting/models/SinusoidPhaseCurve.py
Labels: bug

#201 Resolves #176 with a secondary x-axis
  eureka/S4_generate_lightcurves/plots_s4.py
Labels: enhancement

#190 Always verbose logs, lsq progress, more saves from S4-6
  demos/JWST/S3_miri_lrs_template.ecf
  demos/JWST/S3_nircam_wfss_template.ecf
  demos/JWST/S3_nirspec_fs_template.ecf
  demos/JWST/S4_template.ecf
  demos/JWST/S5_template.ecf
  docs/media/S3_template.ecf
  docs/media/S4_template.ecf
  docs/media/S5_template.ecf
  eureka/S3_data_reduction/background.py
  eureka/S3_data_reduction/bright2flux.py
  eureka/S3_data_reduction/miri.py
  eureka/S3_data_reduction/optspex.py
  eureka/S3_data_reduction/s3_reduce.py
  eureka/S3_data_reduction/wfc3.py
  eureka/S4_generate_lightcurves/s4_genLC.py
  eureka/S5_lightcurve_fitting/fitters.py
  eureka/S5_lightcurve_fitting/lightcurve.py
  eureka/S5_lightcurve_fitting/likelihood.py
  eureka/S5_lightcurve_fitting/models/BatmanModels.py
  eureka/S5_lightcurve_fitting/s5_fit.py
  eureka/S6_planet_spectra/s6_spectra.py
  eureka/lib/astropytable.py
  eureka/lib/clipping.py
  eureka/lib/logedit.py
  eureka/tests/NIRCam_ecfs/S3_NIRCam.ecf
  eureka/tests/NIRCam_ecfs/S4_NIRCam.ecf
  eureka/tests/NIRCam_ecfs/S5_NIRCam.ecf
  eureka/tests/NIRSpec_ecfs/S3_NIRSpec.ecf
  eureka/tests/NIRSpec_ecfs/S4_NIRSpec.ecf
  eureka/tests/NIRSpec_ecfs/S5_NIRSpec.ecf
Labels: enhancement

#229 Moves MAD calculation out of plotting functions and into util.py
  eureka/S3_data_reduction/plots_s3.py
  eureka/S3_data_reduction/s3_reduce.py
  eureka/S4_generate_lightcurves/plots_s4.py
  eureka/S4_generate_lightcurves/s4_genLC.py
  eureka/lib/util.py
Labels: bug, enhancement

#216 Some tweaks for the newest NGTS-10b simulation with a companion star
  eureka/S3_data_reduction/miri.py
  eureka/S4_generate_lightcurves/s4_genLC.py
  eureka/S5_lightcurve_fitting/s5_fit.py
  eureka/lib/clipping.py
Labels: enhancement

#235 Fixing issues with plotting masked data in S3
  eureka/S3_data_reduction/background.py
  eureka/S3_data_reduction/optspex.py
  eureka/S3_data_reduction/plots_s3.py
  eureka/S3_data_reduction/s3_reduce.py
Labels: bug
