Repository kevin218/Eureka, pull requests merged in 2022-08, with the labels that each got.

#441 Smooth curvature, compute clean median flux
  src/eureka/S3_data_reduction/background.py
  src/eureka/S3_data_reduction/nircam.py
  src/eureka/S3_data_reduction/optspex.py
  src/eureka/S3_data_reduction/plots_s3.py
  src/eureka/S3_data_reduction/s3_reduce.py
  src/eureka/S3_data_reduction/straighten.py
  tests/WFC3_ecfs/S3_WFC3.ecf
  tests/WFC3_ecfs/S4_WFC3.ecf
  tests/test_WFC3.py
Labels: bug, enhancement

#459 Handling S3 NaN wavelengths
  src/eureka/S3_data_reduction/plots_s3.py
  src/eureka/S3_data_reduction/s3_reduce.py
  src/eureka/lib/util.py
Labels: enhancement

#454 Drift decorrelation, S6 LaTeX tables, and bug fixes
  demos/HST/S5_wfc3_template.ecf
  demos/HST/S6_wfc3_template.ecf
  demos/HST/s5_fit_par_wfc3_template.epf
  demos/JWST/S3_nircam_wfss_template.ecf
  demos/JWST/S3_nirspec_fs_template.ecf
  demos/JWST/S5_fit_par_template.epf
  demos/JWST/S5_template.ecf
  demos/JWST/S6_template.ecf
  docs/media/S3_out/fig3107_file0_Curvature.png
  docs/media/S3_template.ecf
  docs/media/S5_fit_par_template.epf
  docs/media/S5_out/fig5301_ch0_allanplot_emcee.png
  docs/media/S5_template.ecf
  docs/media/S6_template.ecf
  docs/source/ecf.rst
  docs/source/outputs.rst
  src/eureka/S2_calibrations/s2_calibrate.py
  src/eureka/S3_data_reduction/background.py
  src/eureka/S3_data_reduction/plots_s3.py
  src/eureka/S3_data_reduction/s3_reduce.py
  src/eureka/S3_data_reduction/source_pos.py
  src/eureka/S3_data_reduction/wfc3.py
  src/eureka/S4_generate_lightcurves/generate_LD.py
  src/eureka/S4_generate_lightcurves/plots_s4.py
  src/eureka/S4_generate_lightcurves/s4_genLC.py
  src/eureka/S4_generate_lightcurves/wfc3.py
  src/eureka/S5_lightcurve_fitting/lightcurve.py
  src/eureka/S5_lightcurve_fitting/likelihood.py
  src/eureka/S5_lightcurve_fitting/models/BatmanModels.py
  src/eureka/S5_lightcurve_fitting/models/CentroidModel.py
  src/eureka/S5_lightcurve_fitting/models/ExpRampModel.py
  src/eureka/S5_lightcurve_fitting/models/GPModel.py
  src/eureka/S5_lightcurve_fitting/models/Model.py
  src/eureka/S5_lightcurve_fitting/models/PolynomialModel.py
  src/eureka/S5_lightcurve_fitting/models/SinusoidPhaseCurve.py
  src/eureka/S5_lightcurve_fitting/models/__init__.py
  src/eureka/S5_lightcurve_fitting/plots_s5.py
  src/eureka/S5_lightcurve_fitting/s5_fit.py
  src/eureka/S6_planet_spectra/plots_s6.py
  src/eureka/S6_planet_spectra/s6_spectra.py
  src/eureka/lib/apphot.py
  tests/MIRI_ecfs/S5_MIRI.ecf
  tests/MIRI_ecfs/S6_MIRI.ecf
  tests/MIRI_ecfs/s5_fit_par.epf
  tests/NIRCam_ecfs/S3_NIRCam.ecf
  tests/NIRCam_ecfs/S5_NIRCam.ecf
  tests/NIRCam_ecfs/S5_fit_par.epf
  tests/NIRCam_ecfs/S6_NIRCam.ecf
  tests/NIRSpec_ecfs/S3_NIRSpec.ecf
  tests/NIRSpec_ecfs/S5_NIRSpec.ecf
  tests/NIRSpec_ecfs/S5_fit_par.epf
  tests/test_MIRI.py
  tests/test_NIRCam.py
  tests/test_NIRSpec.py
  tests/test_Photometry_NIRCam.py
Labels: bug, enhancement, LC Fit
