Repository kevin218/Eureka, pull requests merged in 2024-02, with the labels that each got.

#584 Upgrade binData() --> binData_time()
  .github/workflows/draft-pdf.yml
  .github/workflows/flake8_linting.yml
  .github/workflows/pytest_testing.yml
  src/eureka/S5_lightcurve_fitting/lightcurve.py
  src/eureka/S5_lightcurve_fitting/plots_s5.py
  src/eureka/S6_planet_spectra/s6_spectra.py
  src/eureka/lib/util.py
  tests/MIRI_ecfs/S5_MIRI.ecf
  tests/MIRI_ecfs/s5_fit_par.epf
  tests/MIRI_ecfs/s5_fit_par_starry.epf
Labels: bug

#612 Resolved libGL ImportError by removing opencv-python dependency
  .gitignore
  docs/source/faq.rst
  environment_pymc3.yml
  setup.cfg
Labels: documentation

#615 Computing uncertainty on Allan variance plots using mc3 package
  environment.yml
  environment_pymc3.yml
  setup.cfg
  src/eureka/S5_lightcurve_fitting/plots_s5.py
  tests/MIRI_ecfs/S5_MIRI.ecf
  tests/NIRCam_ecfs/S5_NIRCam.ecf
Labels: enhancement, LC Fit

#613 Switching plots from tight_layout to constrained_layout
  src/eureka/S3_data_reduction/plots_s3.py
  src/eureka/S4_generate_lightcurves/plots_s4.py
  src/eureka/S5_lightcurve_fitting/lightcurve.py
  src/eureka/S5_lightcurve_fitting/models/KeplerOrbit.py
  src/eureka/S5_lightcurve_fitting/plots_s5.py
  src/eureka/S6_planet_spectra/plots_s6.py
  src/eureka/lib/plots.py
Labels: bug

#611 Stage 1 Jump Step Parallelization
  demos/JWST/S1_miri_template.ecf
  demos/JWST/S1_nirx_template.ecf
  docs/media/S1_template.ecf
  docs/source/ecf.rst
  src/eureka/S1_detector_processing/s1_process.py
  src/eureka/S5_lightcurve_fitting/__init__.py
  src/eureka/S5_lightcurve_fitting/s5_fit.py
  tests/MIRI_ecfs/S1_MIRI.ecf
Labels: enhancement

#614 Switching from celerite to celerite2
  environment.yml
  environment_pymc3.yml
  setup.cfg
  src/eureka/S5_lightcurve_fitting/fitters.py
  src/eureka/S5_lightcurve_fitting/models/GPModel.py
  src/eureka/lib/gaussian_min.py
  tests/NIRSpec_ecfs/S5_NIRSpec.ecf
  tests/NIRSpec_ecfs/S5_fit_par.epf
  tests/test_NIRSpec.py
Labels: bug, enhancement

#616 Updating instructions for newer exotic-ld versions
  demos/HST/S4_wfc3_template.ecf
  demos/JWST/S4_template.ecf
  docs/media/S4_template.ecf
  docs/source/ecf.rst
  docs/source/installation.rst
  environment.yml
  environment_pymc3.yml
  setup.cfg
  tests/MIRI_ecfs/S4_MIRI.ecf
  tests/NIRCam_ecfs/S4_NIRCam.ecf
  tests/NIRSpec_ecfs/S4_NIRSpec.ecf
  tests/Photometry_NIRCam_ecfs/S4_Photometry_NIRCam.ecf
  tests/WFC3_ecfs/S4_WFC3.ecf
Labels: documentation, enhancement

#622 Fix emcee old_chain for white-light curve fit bug
  src/eureka/S5_lightcurve_fitting/fitters.py
Labels: bug

#556 Removing 390Hz noise from LRS SLITLESSPRISM data
  demos/JWST/S1_miri_template.ecf
  demos/JWST/S1_nirx_template.ecf
  docs/source/ecf.rst
  src/eureka/S1_detector_processing/ramp_fitting.py
  src/eureka/S1_detector_processing/remove390.py
  src/eureka/S1_detector_processing/s1_process.py
  src/eureka/lib/smooth.py
Labels: documentation, enhancement, MIRI

#625 Ms no longer used in starry models; batman `w` parameter no long must be between (0,360); minor tweaks
  docs/source/ecf.rst
  src/eureka/S3_data_reduction/source_pos.py
  src/eureka/S5_lightcurve_fitting/differentiable_models/PyMC3Models.py
  src/eureka/S5_lightcurve_fitting/differentiable_models/StarryModel.py
  src/eureka/S5_lightcurve_fitting/models/BatmanModels.py
Labels: enhancement, LC Fit

#623 Rearranging bright2flux ancillary file look-ups
  src/eureka/S3_data_reduction/bright2flux.py
Labels: bug, enhancement

#624 Adding a PyMC3 compatible GP using celerite2
  src/eureka/S5_lightcurve_fitting/differentiable_models/GPModel.py
  src/eureka/S5_lightcurve_fitting/differentiable_models/PyMC3Models.py
  src/eureka/S5_lightcurve_fitting/differentiable_models/__init__.py
  src/eureka/S5_lightcurve_fitting/gradient_fitters.py
  src/eureka/S5_lightcurve_fitting/s5_fit.py
Labels: enhancement, LC Fit

#598 Allowing for custom stellar intensity files to be fed into S4 for limb darkening calculations
  demos/HST/S4_wfc3_template.ecf
  demos/JWST/Custom_Stellar_Intensity_Files/sample_stellar_intesity.txt
  demos/JWST/S4_template.ecf
  docs/media/S4_template.ecf
  docs/source/ecf.rst
  src/eureka/S3_data_reduction/background.py
  src/eureka/S4_generate_lightcurves/generate_LD.py
  tests/MIRI_ecfs/S4_MIRI.ecf
  tests/NIRCam_ecfs/S4_NIRCam.ecf
  tests/NIRSpec_ecfs/S4_NIRSpec.ecf
  tests/Photometry_NIRCam_ecfs/S4_Photometry_NIRCam.ecf
  tests/WFC3_ecfs/S4_WFC3.ecf
Labels: enhancement
