Repository kevin218/Eureka, pull requests merged in 2024-09, with the labels that each got.

#700 Adding a dark mode to the readthedocs page
  docs/source/_static/css/rtd_dark.css
  docs/source/conf.py
Labels: documentation

#627 Enable modeling of starspots with both Fleck and Starry
  demos/HST/S5_wfc3_template.ecf
  demos/HST/s5_fit_par_wfc3_template.epf
  demos/JWST/S5_fit_par_template.epf
  demos/JWST/S5_template.ecf
  docs/media/S5_fit_par_template.epf
  docs/media/S5_template.ecf
  docs/source/ecf.rst
  environment.yml
  environment_pymc3.yml
  setup.cfg
  src/eureka/S5_lightcurve_fitting/differentiable_models/PyMC3Models.py
  src/eureka/S5_lightcurve_fitting/differentiable_models/StarryModel.py
  src/eureka/S5_lightcurve_fitting/fitters.py
  src/eureka/S5_lightcurve_fitting/gradient_fitters.py
  src/eureka/S5_lightcurve_fitting/models/AstroModel.py
  src/eureka/S5_lightcurve_fitting/models/BatmanModels.py
  src/eureka/S5_lightcurve_fitting/models/FleckModel.py
  src/eureka/S5_lightcurve_fitting/models/Model.py
  src/eureka/S5_lightcurve_fitting/models/__init__.py
  src/eureka/S5_lightcurve_fitting/plots_s5.py
  src/eureka/S5_lightcurve_fitting/s5_fit.py
  src/eureka/lib/citations.py
  src/eureka/lib/util.py
  tests/MIRI_ecfs/S5_MIRI.ecf
  tests/MIRI_ecfs/s5_fit_par.epf
  tests/MIRI_ecfs/s5_fit_par_starry.epf
  tests/test_MIRI.py
Labels: enhancement, LC Fit

#701 Better documenting multi-channel and multi-planet EPF settings
  docs/source/ecf.rst
Labels: documentation, enhancement

#705 Minor bug patches before v1.0
  demos/JWST/S3_miri_photometry_template.ecf
  demos/JWST/S3_nircam_wfss_template.ecf
  environment.yml
  environment_pymc3.yml
  setup.cfg
  src/eureka/S1_detector_processing/group_level.py
  src/eureka/S3_data_reduction/plots_s3.py
  src/eureka/S6_planet_spectra/s6_spectra.py
  src/eureka/lib/centerdriver.py
Labels: bug
