Repository kevin218/Eureka, pull requests merged in 2024-08, with the labels that each got.

#677 Bug patches
  demos/JWST/S3_miri_lrs_template.ecf
  environment.yml
  environment_pymc3.yml
  setup.cfg
  src/eureka/S1_detector_processing/s1_process.py
  src/eureka/lib/util.py
Labels: bug

#682 NIRCam enhancements from v1 testing
  demos/JWST/S1_nirx_template.ecf
  demos/JWST/S2_nircam_wfss_template.ecf
  demos/JWST/S3_nircam_wfss_template.ecf
  demos/JWST/S4_template.ecf
  src/eureka/S4_generate_lightcurves/generate_LD.py
  src/eureka/S4_generate_lightcurves/plots_s4.py
Labels: bug, NIRCam

#654 Enables custom bad pixel masks (S1), user supplied wavelength files (S4), adds joint white light curve fitting parameters to docs (S5)
  demos/HST/S4_wfc3_template.ecf
  demos/JWST/S1_nirx_template.ecf
  demos/JWST/S4_template.ecf
  demos/JWST/S5_template.ecf
  docs/media/S1_template.ecf
  docs/media/S4_template.ecf
  docs/source/ecf.rst
  src/eureka/S1_detector_processing/s1_meta.py
  src/eureka/S1_detector_processing/s1_process.py
  src/eureka/S4_generate_lightcurves/s4_genLC.py
  src/eureka/S4_generate_lightcurves/s4_meta.py
Labels: documentation, enhancement

#693 Two Enhancements from Testing v1.0
  demos/HST/S6_wfc3_template.ecf
  demos/JWST/S6_template.ecf
  docs/media/S6_template.ecf
  docs/source/ecf.rst
  src/eureka/S3_data_reduction/miri.py
  src/eureka/S3_data_reduction/s3_meta.py
  src/eureka/S3_data_reduction/wfc3.py
  src/eureka/S6_planet_spectra/s6_meta.py
  src/eureka/S6_planet_spectra/s6_spectra.py
  src/eureka/lib/util.py
Labels: enhancement

#686 Bug patches and docs improvements for v1.0
  demos/HST/S5_wfc3_template.ecf
  demos/HST/s5_fit_par_wfc3_template.epf
  demos/JWST/S5_fit_par_template.epf
  demos/JWST/S5_template.ecf
  docs/media/S5_fit_par_template.epf
  docs/media/S5_template.ecf
  docs/source/ecf.rst
  docs/source/installation.rst
  environment.yml
  src/eureka/S1_detector_processing/s1_meta.py
  src/eureka/S3_data_reduction/nircam.py
  src/eureka/S3_data_reduction/plots_s3.py
  src/eureka/S5_lightcurve_fitting/differentiable_models/AstroModel.py
  src/eureka/S5_lightcurve_fitting/differentiable_models/ExpRampModel.py
  src/eureka/S5_lightcurve_fitting/differentiable_models/GPModel.py
  src/eureka/S5_lightcurve_fitting/differentiable_models/HSTRampModel.py
  src/eureka/S5_lightcurve_fitting/differentiable_models/PyMC3Models.py
  src/eureka/S5_lightcurve_fitting/differentiable_models/QuasiLambertianPhaseCurve.py
  src/eureka/S5_lightcurve_fitting/differentiable_models/SinusoidPhaseCurve.py
  src/eureka/S5_lightcurve_fitting/differentiable_models/StarryModel.py
  src/eureka/S5_lightcurve_fitting/fitters.py
  src/eureka/S5_lightcurve_fitting/gradient_fitters.py
  src/eureka/S5_lightcurve_fitting/models/AstroModel.py
  src/eureka/S5_lightcurve_fitting/models/ExpRampModel.py
  src/eureka/S5_lightcurve_fitting/models/HSTRampModel.py
  src/eureka/S5_lightcurve_fitting/models/QuasiLambertianPhaseCurve.py
  src/eureka/S5_lightcurve_fitting/models/SinusoidPhaseCurve.py
  src/eureka/S5_lightcurve_fitting/s5_fit.py
  src/eureka/S5_lightcurve_fitting/s5_meta.py
  src/eureka/S6_planet_spectra/s6_spectra.py
  src/eureka/lib/plots.py
  tests/MIRI_ecfs/POET/s5_POET.epf
  tests/MIRI_ecfs/s5_fit_par.epf
  tests/MIRI_ecfs/s5_fit_par_starry.epf
  tests/NIRCam_ecfs/POET/S5_POET.epf
  tests/NIRCam_ecfs/S5_fit_par.epf
  tests/NIRSpec_ecfs/S5_fit_par.epf
  tests/Photometry_NIRCam_ecfs/S5_fit_par.epf
  tests/test_lightcurve_fitting.py
Labels: bug, documentation

#689 Handling missing scan segments in HST data
  src/eureka/S3_data_reduction/plots_s3.py
  src/eureka/S3_data_reduction/wfc3.py
Labels: bug, enhancement, WFC3
